[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#1F2937"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
allowRunOnSave = true

[browser]
gatherUsageStats = false